## Importing and cleaning files

```{r}
### Initial import of files
gdp <- read_excel('gdp.xlsx')
pop <- read_excel('population.xlsx')
school <- read_excel('school.xlsx')
regions <- read_excel('regions.xlsx')

### Rename columns to remove decimal points
colnames(gdp) <- substr(names(gdp), 1, 4)
colnames(pop) <- substr(names(pop), 1, 4)
colnames(school) <- substr(names(school), 1, 4)

### Make one row for year column
gdp <- gather(gdp, "Year", "GDP", 2:length(colnames(gdp)))
pop <- gather(pop, "Year", "Population", 2:length(colnames(pop)))
school <- gather(school, "Year", "SchoolYears", 2:length(colnames(school)))

### Remove all other columns not needed to match country to region
regions <- regions[-c(3:84)]

### Rename the first columns in order to easily match with regions
colnames(gdp)[1] <- "Country"
colnames(pop)[1] <- "Country"
colnames(school)[1] <- "Country"

### Merge all data into one table
data <- merge(school, regions, by="Country")
data <- merge(data, gdp, by=c("Country", "Year"))
data <- merge(data, pop, by=c("Country", "Year"))

### Make square root of population to use for circle radius
data$Population.sqrt <- sqrt(data[,'Population'])

### Remove any rows with NA data
data <- na.omit(data)
```

```{r}
### Printing out plot to test ideas
ggplot(aes(x = SchoolYears, y = GDP, size=Population, color=Region), data = subset(data, Year = '1980')) + 
  geom_point(alpha = 5/10)
#  scale_y_continuous(limits = c(0,109000), breaks = seq(0, 109000, 10000))
```

```{r}
write.csv(data, file = 'data.csv', row.names = FALSE)
```

